// From https://bitbucket.org/atlassian/atlaskitmk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js

const countries = [
  { countryShortName: "AD", countryName: "Andorra", countryCode: "376" },
  {
    countryShortName: "AE",
    countryName: "United Arab Emirates",
    countryCode: "971",
  },
  { countryShortName: "AF", countryName: "Afghanistan", countryCode: "93" },
  {
    countryShortName: "AG",
    countryName: "Antigua and Barbuda",
    countryCode: "1268",
  },
  { countryShortName: "AI", countryName: "Anguilla", countryCode: "1264" },
  { countryShortName: "AL", countryName: "Albania", countryCode: "355" },
  { countryShortName: "AM", countryName: "Armenia", countryCode: "374" },
  { countryShortName: "AO", countryName: "Angola", countryCode: "244" },
  { countryShortName: "AQ", countryName: "Antarctica", countryCode: "672" },
  { countryShortName: "AR", countryName: "Argentina", countryCode: "54" },
  {
    countryShortName: "AS",
    countryName: "American Samoa",
    countryCode: "1684",
  },
  { countryShortName: "AT", countryName: "Austria", countryCode: "43" },
  {
    countryShortName: "AU",
    countryName: "Australia",
    countryCode: "61",
  },
  { countryShortName: "AW", countryName: "Aruba", countryCode: "297" },
  { countryShortName: "AX", countryName: "Alland Islands", countryCode: "358" },
  { countryShortName: "AZ", countryName: "Azerbaijan", countryCode: "994" },
  {
    countryShortName: "BA",
    countryName: "Bosnia and Herzegovina",
    countryCode: "387",
  },
  { countryShortName: "BB", countryName: "Barbados", countryCode: "1246" },
  { countryShortName: "BD", countryName: "Bangladesh", countryCode: "880" },
  { countryShortName: "BE", countryName: "Belgium", countryCode: "32" },
  { countryShortName: "BF", countryName: "Burkina Faso", countryCode: "226" },
  { countryShortName: "BG", countryName: "Bulgaria", countryCode: "359" },
  { countryShortName: "BH", countryName: "Bahrain", countryCode: "973" },
  { countryShortName: "BI", countryName: "Burundi", countryCode: "257" },
  { countryShortName: "BJ", countryName: "Benin", countryCode: "229" },
  {
    countryShortName: "BL",
    countryName: "Saint Barthelemy",
    countryCode: "590",
  },
  { countryShortName: "BM", countryName: "Bermuda", countryCode: "1441" },
  {
    countryShortName: "BN",
    countryName: "Brunei Darussalam",
    countryCode: "673",
  },
  { countryShortName: "BO", countryName: "Bolivia", countryCode: "591" },
  { countryShortName: "BR", countryName: "Brazil", countryCode: "55" },
  { countryShortName: "BS", countryName: "Bahamas", countryCode: "1242" },
  { countryShortName: "BT", countryName: "Bhutan", countryCode: "975" },
  { countryShortName: "BV", countryName: "Bouvet Island", countryCode: "47" },
  { countryShortName: "BW", countryName: "Botswana", countryCode: "267" },
  { countryShortName: "BY", countryName: "Belarus", countryCode: "375" },
  { countryShortName: "BZ", countryName: "Belize", countryCode: "501" },
  {
    countryShortName: "CA",
    countryName: "Canada",
    countryCode: "1",
  },
  {
    countryShortName: "CC",
    countryName: "Cocos (Keeling) Islands",
    countryCode: "61",
  },
  {
    countryShortName: "CD",
    countryName: "Congo, Democratic Republic of the",
    countryCode: "243",
  },
  {
    countryShortName: "CF",
    countryName: "Central African Republic",
    countryCode: "236",
  },
  {
    countryShortName: "CG",
    countryName: "Congo, Republic of the",
    countryCode: "242",
  },
  { countryShortName: "CH", countryName: "Switzerland", countryCode: "41" },
  { countryShortName: "CI", countryName: "Cote d'Ivoire", countryCode: "225" },
  { countryShortName: "CK", countryName: "Cook Islands", countryCode: "682" },
  { countryShortName: "CL", countryName: "Chile", countryCode: "56" },
  { countryShortName: "CM", countryName: "Cameroon", countryCode: "237" },
  { countryShortName: "CN", countryName: "China", countryCode: "86" },
  { countryShortName: "CO", countryName: "Colombia", countryCode: "57" },
  { countryShortName: "CR", countryName: "Costa Rica", countryCode: "506" },
  { countryShortName: "CU", countryName: "Cuba", countryCode: "53" },
  { countryShortName: "CV", countryName: "Cape Verde", countryCode: "238" },
  { countryShortName: "CW", countryName: "Curacao", countryCode: "599" },
  {
    countryShortName: "CX",
    countryName: "Christmas Island",
    countryCode: "61",
  },
  { countryShortName: "CY", countryName: "Cyprus", countryCode: "357" },
  { countryShortName: "CZ", countryName: "Czech Republic", countryCode: "420" },
  {
    countryShortName: "DE",
    countryName: "Germany",
    countryCode: "49",
  },
  { countryShortName: "DJ", countryName: "Djibouti", countryCode: "253" },
  { countryShortName: "DK", countryName: "Denmark", countryCode: "45" },
  { countryShortName: "DM", countryName: "Dominica", countryCode: "1767" },
  {
    countryShortName: "DO",
    countryName: "Dominican Republic",
    countryCode: "1809",
  },
  { countryShortName: "DZ", countryName: "Algeria", countryCode: "213" },
  { countryShortName: "EC", countryName: "Ecuador", countryCode: "593" },
  { countryShortName: "EE", countryName: "Estonia", countryCode: "372" },
  { countryShortName: "EG", countryName: "Egypt", countryCode: "20" },
  { countryShortName: "EH", countryName: "Western Sahara", countryCode: "212" },
  { countryShortName: "ER", countryName: "Eritrea", countryCode: "291" },
  { countryShortName: "ES", countryName: "Spain", countryCode: "34" },
  { countryShortName: "ET", countryName: "Ethiopia", countryCode: "251" },
  { countryShortName: "FI", countryName: "Finland", countryCode: "358" },
  { countryShortName: "FJ", countryName: "Fiji", countryCode: "679" },
  {
    countryShortName: "FK",
    countryName: "Falkland Islands (Malvinas)",
    countryCode: "500",
  },
  {
    countryShortName: "FM",
    countryName: "Micronesia, Federated States of",
    countryCode: "691",
  },
  { countryShortName: "FO", countryName: "Faroe Islands", countryCode: "298" },
  {
    countryShortName: "FR",
    countryName: "France",
    countryCode: "33",
  },
  { countryShortName: "GA", countryName: "Gabon", countryCode: "241" },
  { countryShortName: "GB", countryName: "United Kingdom", countryCode: "44" },
  { countryShortName: "GD", countryName: "Grenada", countryCode: "1473" },
  { countryShortName: "GE", countryName: "Georgia", countryCode: "995" },
  { countryShortName: "GF", countryName: "French Guiana", countryCode: "594" },
  { countryShortName: "GG", countryName: "Guernsey", countryCode: "44" },
  { countryShortName: "GH", countryName: "Ghana", countryCode: "233" },
  { countryShortName: "GI", countryName: "Gibraltar", countryCode: "350" },
  { countryShortName: "GL", countryName: "Greenland", countryCode: "299" },
  { countryShortName: "GM", countryName: "Gambia", countryCode: "220" },
  { countryShortName: "GN", countryName: "Guinea", countryCode: "224" },
  { countryShortName: "GP", countryName: "Guadeloupe", countryCode: "590" },
  {
    countryShortName: "GQ",
    countryName: "Equatorial Guinea",
    countryCode: "240",
  },
  { countryShortName: "GR", countryName: "Greece", countryCode: "30" },
  {
    countryShortName: "GS",
    countryName: "South Georgia and the South Sandwich Islands",
    countryCode: "500",
  },
  { countryShortName: "GT", countryName: "Guatemala", countryCode: "502" },
  { countryShortName: "GU", countryName: "Guam", countryCode: "1671" },
  { countryShortName: "GW", countryName: "Guinea-Bissau", countryCode: "245" },
  { countryShortName: "GY", countryName: "Guyana", countryCode: "592" },
  { countryShortName: "HK", countryName: "Hong Kong", countryCode: "852" },
  {
    countryShortName: "HM",
    countryName: "Heard Island and McDonald Islands",
    countryCode: "672",
  },
  { countryShortName: "HN", countryName: "Honduras", countryCode: "504" },
  { countryShortName: "HR", countryName: "Croatia", countryCode: "385" },
  { countryShortName: "HT", countryName: "Haiti", countryCode: "509" },
  { countryShortName: "HU", countryName: "Hungary", countryCode: "36" },
  { countryShortName: "ID", countryName: "Indonesia", countryCode: "62" },
  { countryShortName: "IE", countryName: "Ireland", countryCode: "353" },
  { countryShortName: "IL", countryName: "Israel", countryCode: "972" },
  { countryShortName: "IM", countryName: "Isle of Man", countryCode: "44" },
  { countryShortName: "IN", countryName: "India", countryCode: "91" },
  {
    countryShortName: "IO",
    countryName: "British Indian Ocean Territory",
    countryCode: "246",
  },
  { countryShortName: "IQ", countryName: "Iraq", countryCode: "964" },
  {
    countryShortName: "IR",
    countryName: "Iran, Islamic Republic of",
    countryCode: "98",
  },
  { countryShortName: "IS", countryName: "Iceland", countryCode: "354" },
  { countryShortName: "IT", countryName: "Italy", countryCode: "39" },
  { countryShortName: "JE", countryName: "Jersey", countryCode: "44" },
  { countryShortName: "JM", countryName: "Jamaica", countryCode: "1876" },
  { countryShortName: "JO", countryName: "Jordan", countryCode: "962" },
  {
    countryShortName: "JP",
    countryName: "Japan",
    countryCode: "81",
  },
  { countryShortName: "KE", countryName: "Kenya", countryCode: "254" },
  { countryShortName: "KG", countryName: "Kyrgyzstan", countryCode: "996" },
  { countryShortName: "KH", countryName: "Cambodia", countryCode: "855" },
  { countryShortName: "KI", countryName: "Kiribati", countryCode: "686" },
  { countryShortName: "KM", countryName: "Comoros", countryCode: "269" },
  {
    countryShortName: "KN",
    countryName: "Saint Kitts and Nevis",
    countryCode: "1869",
  },
  {
    countryShortName: "KP",
    countryName: "Korea, Democratic People's Republic of",
    countryCode: "850",
  },
  {
    countryShortName: "KR",
    countryName: "Korea, Republic of",
    countryCode: "82",
  },
  { countryShortName: "KW", countryName: "Kuwait", countryCode: "965" },
  {
    countryShortName: "KY",
    countryName: "Cayman Islands",
    countryCode: "1345",
  },
  { countryShortName: "KZ", countryName: "Kazakhstan", countryCode: "7" },
  {
    countryShortName: "LA",
    countryName: "Lao People's Democratic Republic",
    countryCode: "856",
  },
  { countryShortName: "LB", countryName: "Lebanon", countryCode: "961" },
  { countryShortName: "LC", countryName: "Saint Lucia", countryCode: "1758" },
  { countryShortName: "LI", countryName: "Liechtenstein", countryCode: "423" },
  { countryShortName: "LK", countryName: "Sri Lanka", countryCode: "94" },
  { countryShortName: "LR", countryName: "Liberia", countryCode: "231" },
  { countryShortName: "LS", countryName: "Lesotho", countryCode: "266" },
  { countryShortName: "LT", countryName: "Lithuania", countryCode: "370" },
  { countryShortName: "LU", countryName: "Luxembourg", countryCode: "352" },
  { countryShortName: "LV", countryName: "Latvia", countryCode: "371" },
  { countryShortName: "LY", countryName: "Libya", countryCode: "218" },
  { countryShortName: "MA", countryName: "Morocco", countryCode: "212" },
  { countryShortName: "MC", countryName: "Monaco", countryCode: "377" },
  {
    countryShortName: "MD",
    countryName: "Moldova, Republic of",
    countryCode: "373",
  },
  { countryShortName: "ME", countryName: "Montenegro", countryCode: "382" },
  {
    countryShortName: "MF",
    countryName: "Saint Martin (French part)",
    countryCode: "590",
  },
  { countryShortName: "MG", countryName: "Madagascar", countryCode: "261" },
  {
    countryShortName: "MH",
    countryName: "Marshall Islands",
    countryCode: "692",
  },
  {
    countryShortName: "MK",
    countryName: "Macedonia, the Former Yugoslav Republic of",
    countryCode: "389",
  },
  { countryShortName: "ML", countryName: "Mali", countryCode: "223" },
  { countryShortName: "MM", countryName: "Myanmar", countryCode: "95" },
  { countryShortName: "MN", countryName: "Mongolia", countryCode: "976" },
  { countryShortName: "MO", countryName: "Macao", countryCode: "853" },
  {
    countryShortName: "MP",
    countryName: "Northern Mariana Islands",
    countryCode: "1670",
  },
  { countryShortName: "MQ", countryName: "Martinique", countryCode: "596" },
  { countryShortName: "MR", countryName: "Mauritania", countryCode: "222" },
  { countryShortName: "MS", countryName: "Montserrat", countryCode: "1664" },
  { countryShortName: "MT", countryName: "Malta", countryCode: "356" },
  { countryShortName: "MU", countryName: "Mauritius", countryCode: "230" },
  { countryShortName: "MV", countryName: "Maldives", countryCode: "960" },
  { countryShortName: "MW", countryName: "Malawi", countryCode: "265" },
  { countryShortName: "MX", countryName: "Mexico", countryCode: "52" },
  { countryShortName: "MY", countryName: "Malaysia", countryCode: "60" },
  { countryShortName: "MZ", countryName: "Mozambique", countryCode: "258" },
  { countryShortName: "NA", countryName: "Namibia", countryCode: "264" },
  { countryShortName: "NC", countryName: "New Caledonia", countryCode: "687" },
  { countryShortName: "NE", countryName: "Niger", countryCode: "227" },
  { countryShortName: "NF", countryName: "Norfolk Island", countryCode: "672" },
  { countryShortName: "NG", countryName: "Nigeria", countryCode: "234" },
  { countryShortName: "NI", countryName: "Nicaragua", countryCode: "505" },
  { countryShortName: "NL", countryName: "Netherlands", countryCode: "31" },
  { countryShortName: "NO", countryName: "Norway", countryCode: "47" },
  { countryShortName: "NP", countryName: "Nepal", countryCode: "977" },
  { countryShortName: "NR", countryName: "Nauru", countryCode: "674" },
  { countryShortName: "NU", countryName: "Niue", countryCode: "683" },
  { countryShortName: "NZ", countryName: "New Zealand", countryCode: "64" },
  { countryShortName: "OM", countryName: "Oman", countryCode: "968" },
  { countryShortName: "PA", countryName: "Panama", countryCode: "507" },
  { countryShortName: "PE", countryName: "Peru", countryCode: "51" },
  {
    countryShortName: "PF",
    countryName: "French Polynesia",
    countryCode: "689",
  },
  {
    countryShortName: "PG",
    countryName: "Papua New Guinea",
    countryCode: "675",
  },
  { countryShortName: "PH", countryName: "Philippines", countryCode: "63" },
  { countryShortName: "PK", countryName: "Pakistan", countryCode: "92" },
  { countryShortName: "PL", countryName: "Poland", countryCode: "48" },
  {
    countryShortName: "PM",
    countryName: "Saint Pierre and Miquelon",
    countryCode: "508",
  },
  { countryShortName: "PN", countryName: "Pitcairn", countryCode: "870" },
  { countryShortName: "PR", countryName: "Puerto Rico", countryCode: "1" },
  {
    countryShortName: "PS",
    countryName: "Palestine, State of",
    countryCode: "970",
  },
  { countryShortName: "PT", countryName: "Portugal", countryCode: "351" },
  { countryShortName: "PW", countryName: "Palau", countryCode: "680" },
  { countryShortName: "PY", countryName: "Paraguay", countryCode: "595" },
  { countryShortName: "QA", countryName: "Qatar", countryCode: "974" },
  { countryShortName: "RE", countryName: "Reunion", countryCode: "262" },
  { countryShortName: "RO", countryName: "Romania", countryCode: "40" },
  { countryShortName: "RS", countryName: "Serbia", countryCode: "381" },
  {
    countryShortName: "RU",
    countryName: "Russian Federation",
    countryCode: "7",
  },
  { countryShortName: "RW", countryName: "Rwanda", countryCode: "250" },
  { countryShortName: "SA", countryName: "Saudi Arabia", countryCode: "966" },
  {
    countryShortName: "SB",
    countryName: "Solomon Islands",
    countryCode: "677",
  },
  { countryShortName: "SC", countryName: "Seychelles", countryCode: "248" },
  { countryShortName: "SD", countryName: "Sudan", countryCode: "249" },
  { countryShortName: "SE", countryName: "Sweden", countryCode: "46" },
  { countryShortName: "SG", countryName: "Singapore", countryCode: "65" },
  { countryShortName: "SH", countryName: "Saint Helena", countryCode: "290" },
  { countryShortName: "SI", countryName: "Slovenia", countryCode: "386" },
  {
    countryShortName: "SJ",
    countryName: "Svalbard and Jan Mayen",
    countryCode: "47",
  },
  { countryShortName: "SK", countryName: "Slovakia", countryCode: "421" },
  { countryShortName: "SL", countryName: "Sierra Leone", countryCode: "232" },
  { countryShortName: "SM", countryName: "San Marino", countryCode: "378" },
  { countryShortName: "SN", countryName: "Senegal", countryCode: "221" },
  { countryShortName: "SO", countryName: "Somalia", countryCode: "252" },
  { countryShortName: "SR", countryName: "Suriname", countryCode: "597" },
  { countryShortName: "SS", countryName: "South Sudan", countryCode: "211" },
  {
    countryShortName: "ST",
    countryName: "Sao Tome and Principe",
    countryCode: "239",
  },
  { countryShortName: "SV", countryName: "El Salvador", countryCode: "503" },
  {
    countryShortName: "SX",
    countryName: "Sint Maarten (Dutch part)",
    countryCode: "1721",
  },
  {
    countryShortName: "SY",
    countryName: "Syrian Arab Republic",
    countryCode: "963",
  },
  { countryShortName: "SZ", countryName: "Swaziland", countryCode: "268" },
  {
    countryShortName: "TC",
    countryName: "Turks and Caicos Islands",
    countryCode: "1649",
  },
  { countryShortName: "TD", countryName: "Chad", countryCode: "235" },
  {
    countryShortName: "TF",
    countryName: "French Southern Territories",
    countryCode: "262",
  },
  { countryShortName: "TG", countryName: "Togo", countryCode: "228" },
  { countryShortName: "TH", countryName: "Thailand", countryCode: "66" },
  { countryShortName: "TJ", countryName: "Tajikistan", countryCode: "992" },
  { countryShortName: "TK", countryName: "Tokelau", countryCode: "690" },
  { countryShortName: "TL", countryName: "Timor-Leste", countryCode: "670" },
  { countryShortName: "TM", countryName: "Turkmenistan", countryCode: "993" },
  { countryShortName: "TN", countryName: "Tunisia", countryCode: "216" },
  { countryShortName: "TO", countryName: "Tonga", countryCode: "676" },
  { countryShortName: "TR", countryName: "Turkey", countryCode: "90" },
  {
    countryShortName: "TT",
    countryName: "Trinidad and Tobago",
    countryCode: "1868",
  },
  { countryShortName: "TV", countryName: "Tuvalu", countryCode: "688" },
  {
    countryShortName: "TW",
    countryName: "Taiwan, Province of China",
    countryCode: "886",
  },
  {
    countryShortName: "TZ",
    countryName: "United Republic of Tanzania",
    countryCode: "255",
  },
  { countryShortName: "UA", countryName: "Ukraine", countryCode: "380" },
  { countryShortName: "UG", countryName: "Uganda", countryCode: "256" },
  {
    countryShortName: "US",
    countryName: "United States",
    countryCode: "1",
  },
  { countryShortName: "UY", countryName: "Uruguay", countryCode: "598" },
  { countryShortName: "UZ", countryName: "Uzbekistan", countryCode: "998" },
  {
    countryShortName: "VA",
    countryName: "Holy See (Vatican City State)",
    countryCode: "379",
  },
  {
    countryShortName: "VC",
    countryName: "Saint Vincent and the Grenadines",
    countryCode: "1784",
  },
  { countryShortName: "VE", countryName: "Venezuela", countryCode: "58" },
  {
    countryShortName: "VG",
    countryName: "British Virgin Islands",
    countryCode: "1284",
  },
  {
    countryShortName: "VI",
    countryName: "US Virgin Islands",
    countryCode: "1340",
  },
  { countryShortName: "VN", countryName: "Vietnam", countryCode: "84" },
  { countryShortName: "VU", countryName: "Vanuatu", countryCode: "678" },
  {
    countryShortName: "WF",
    countryName: "Wallis and Futuna",
    countryCode: "681",
  },
  { countryShortName: "WS", countryName: "Samoa", countryCode: "685" },
  { countryShortName: "XK", countryName: "Kosovo", countryCode: "383" },
  { countryShortName: "YE", countryName: "Yemen", countryCode: "967" },
  { countryShortName: "YT", countryName: "Mayotte", countryCode: "262" },
  { countryShortName: "ZA", countryName: "South Africa", countryCode: "27" },
  { countryShortName: "ZM", countryName: "Zambia", countryCode: "260" },
  { countryShortName: "ZW", countryName: "Zimbabwe", countryCode: "263" },
] as const;

export { countries };
